apiVersion: autoscaling/v2beta1 
kind: HorizontalPodAutoscaler 
metadata: 
  name: application
spec: 
  maxReplicas: 15 
  minReplicas: 10
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: application 
  metrics: 
  - type: Resource 
    resource: 
      name: cpu 
      target:
        type: Utilization
        averageUtilization: 50
      name: memory
        type: Utilization
        averageUtilization: 60
